# Site settings
title: haska 博客
email: haska1025@outlook.com
description: 学习记录
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  haska1025

include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Build settings
encoding: utf-8
#markdown: rdiscount
# markdown: kramdown
# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
#highlighter: rouge
highlighter: pygments
